### ISSUE TITLE
R-type Instructions

### ISSUE THREAD

**Issue by luan1221** [luan1221/ProjetoHardware#1]
- [x] add rd, rt, rs
- [x] sub rd, rt, rs
- [x] and rd, rs, rt
- [x] div rs, rt
- [x] mult rs,rt
- [x] mfhi rd
- [x] mflo rd
- [x] jr rs
- [x] sll rd, rt, shamt
- [x] sllv rd, rs, rt
- [x] slt rd, rs, rt
- [x] sra rd, rt, shamt
- [x] srav rd, rs, rt
- [x] srl rd, rt, shamt
- [x] break
- [x] Rte
- [x] xchg rs,rt

**Comment by pvsaragao** [comment]
FECHOU
